### DISCUSSION TITLE
双拼也加入模糊音设置

### DISCUSSION THREAD

**Discussion by xinhui1209** [gaboolic/rime-frost#266] [Show and tell]
```
# 拼写设定
speller:
  # alphabet 中加入计算器所需的所有字符，以防止它们被立刻上屏
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA0123456789`/-+*!^().,
  initials: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"  # 第一位<空格>是拼音之间的分隔符；第二位<'>表示可以手动输入单引号来分割拼音。
  algebra:
 # 1. 添加模糊音规则（平翘舌互转）
    - derive/^([zcs])h/$1/          # zh/ch/sh → z/c/s
    - derive/^([zcs])([^h])/$1h$2/  # z/c/s → zh/ch/sh（反向转换）

  # 2. 其他常用模糊音
#- derive/ang$/an/       # ang → an
#- derive/an$/ang/       # an → ang
#- derive/eng$/en/       # eng → en
#- derive/en$/eng/       # en → eng
#- derive/ing$/in/        # ing → in
#- derive/in$/ing/        # in → ing
# 3. 原有双拼转换规则（勿动顺序）
    - erase/^xx$/
    - derive/^([jqxy])u$/$1v/
    - derive/^([aoe])([ioun])$/$1$1$2/
    - xform/^([aoe])(ng)?$/$1$1$2/
    - xform/iu$/Ⓠ/
    - xform/(.)ei$/$1Ⓦ/
    - xform/uan$/Ⓡ/
    - xform/[uv]e$/Ⓣ/
    - xform/un$/Ⓨ/
    - xform/^sh/Ⓤ/
    - xform/^ch/Ⓘ/
....
```
