### ISSUE TITLE
如何在小企鹅输入法中使用辅助码？

### ISSUE THREAD

**Issue by CKlimeths** [gaboolic/rime-frost#104]
在安卓端，我通过小企鹅输入法（Fcitx5 for Android）的rime插件使用白霜方案，由于小企鹅输入法使用原有的 `` ` `` 打不出辅助码，想把辅助码引导符改到 `,` 上，但是打出逗号和辅助码之后没有任何筛选效果，如下图。

![IMG_20241209_152909](https://github.com/user-attachments/assets/36381c2d-36e4-4188-a778-882141e54a16)

下面是custom.yaml文件内容

```yaml
# rime_frost_double_pinyin_flypy.custom.yaml
patch:
  engine/filters/@8: lua_filter@*aux_code@flypy #鹤形辅助码
  translator/preedit_format: []
  key_binder/search: ","
  speller/alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA,/
```

**Comment by CKlimeths** [comment]
> 你先试试 直接在方案里修改，排除下patch写法的原因

试了一下直接在方案中修改，没有改变。我查看了build文件夹下生成的方案文件，patch写法和直接改方案的生成结果是一样的。

后又看了一下 lua 文件夹下的 aux_code.lua 文件，发现以下代码片段：

```lua
    -- 設定預設觸發鍵為分號，並從配置中讀取自訂的觸發鍵
    env.trigger_key = config:get_string("key_binder/aux_code_trigger") or "`"
    -- 设定是否显示辅助码，默认为显示
    env.show_aux_notice = config:get_string("key_binder/show_aux_notice") or 'true'
```

lua脚本中读取的配置名是 `key_binder/aux_code_trigger` ，所以使用 `key_binder/search` 表示辅助码引导符是没用的🤣。

将配置修改为下面的样子就可以使用 `,` 引导辅助码了。

```yaml
patch:
  engine/filters/@8: lua_filter@*aux_code@flypy
  translator/preedit_format: []
  key_binder/aux_code_trigger: ","
  speller/alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA,/
```

建议作者把方案中的代码和注释也修正一下，像我这样想改配置的人容易被带歪的说🤣。
