### ISSUE TITLE
如何设置初始状态下为英文

### ISSUE THREAD

**Issue by laylayboy** [gaboolic/rime-frost#109]
如题 ，如何设置初始状态默认为英文

**Comment by gaboolic** [comment]
```
# 开关
# reset: 默认状态。注释掉后，切换窗口时不会重置到默认状态。
# states: 方案选单显示的名称。可以注释掉，仍可以通过快捷键切换。
# abbrev: 默认的缩写取 states 的第一个字符，abbrev 可自定义一个字符
switches:
  - name: ascii_mode
    states: [ 中, Ａ ]
  - name: ascii_punct  # 中英标点
    states: [ ¥, $ ]
  - name: traditionalization
    states: [ 简, 繁 ]
  - name: emoji
    states: [ 💀, 😄 ]
    reset: 1
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: search_single_char  # search.lua 的功能开关，辅码查词时是否单字优先
    abbrev: [词, 单]
    states: [正常, 单字]
```
  - name: ascii_mode
    states: [ 中, Ａ ]
    后面加reset: 1
