### ISSUE TITLE
如何关闭部分词库

### ISSUE THREAD

**Issue by KF-14** [gaboolic/rime-frost#138]
在中文状态下输入大写英文字母时，如果是没有收录的缩写形式就不会出现候选词。因此我想关闭这个大写字母的词库，有什么方式可以做到吗

**Comment by gaboolic** [comment]
https://github.com/gaboolic/rime-frost/blob/master/rime_frost.schema.yaml
```
# 输入引擎
engine:
  processors:
    - lua_processor@*select_character          # 以词定字
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@radical_lookup  # 部件拆字自定义 tag
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - lua_translator@*date_translator    # 时间、日期、星期
    - lua_translator@*lunar              # 农历
    - table_translator@custom_phrase    # 自定义短语 custom_phrase.txt
    - table_translator@melt_eng         # 英文输入
    - table_translator@cn_en            # 中英混合词汇
    
```

    - table_translator@melt_eng         # 英文输入
    - table_translator@cn_en            # 中英混合词汇
你看下应该在这里
