### ISSUE TITLE
方案选单hotkeys:  F4建议修改，和EXCEL函数公式锁定热键重复。

### ISSUE THREAD

**Issue by bujchen** [gaboolic/rime-frost#153]
方案选单hotkeys:  F4建议修改，和EXCEL函数公式锁定热键重复。

**Comment by gaboolic** [comment]
这个是rime默认的，可以在default.yaml中修改 或者打补丁修改

```
# 方案选单相关
switcher:
  caption: 「方案选单」
  hotkeys:
    - F4
    - Control+grave
    - Control+Shift+grave
    
```
