### ISSUE TITLE
请问macos上，选字框，如何从竖屏改成横屏啊？

### ISSUE THREAD

**Issue by zhangyc310** [gaboolic/rime-frost#168]
weasel.yaml中，这些地方这样修改了，但还是竖屏，不是横屏。请问如何才能把输入框从竖屏改成横屏啊？
```
style:
  fullscreen: false                        # 候选窗口全屏显示：true；false
  horizontal: true                         # 候选项横排：true；false
  vertical_text: false                     # 竖排文本：true；false
  text_orientation: horizontal             # 文本排列方向，效果和 `vertical_text` 相同：horizontal；vertical
  vertical_text_left_to_right: false       # 竖排方向是否从左到右：true；false
  vertical_text_with_wrap: false           # 文本竖排模式下，自动换行：true；false
  vertical_auto_reverse: false             # 文本竖排模式下，候选窗口位于光标上方时倒序排列：true；false

layout:
   type: horizontal                       # 布局设置，效果和 style 下的设置相同：
                                           # horizontal（横向）；vertical（竖向） ; vertical_text（竖排文本） ; vertical+fullscreen（全屏） ; horizontal+fullscreen（横向全屏）
```
