### ISSUE TITLE
请问，在fcitx5-android上使用白霜词库，加载万象语言模型，输入法失效

### ISSUE THREAD

**Issue by rullineter** [gaboolic/rime-frost#184]
fcitx5-android 版本：0.1.1

plugin.rime 版本：0.1.1

白霜词库 版本：0.0.5

RIME-LMDG 版本：amz-v2n3m1-zh-hans.gram

配置文件直接在rime_frost.schema.yaml最后加上：
```
__include: octagram   #启用语法模型
#语法模型
octagram:
  __patch:
    grammar:
      language: amz-v2n3m1-zh-hans  
      collocation_max_length: 5
      collocation_min_length: 2
    translator/contextual_suggestions: true
    translator/max_homophones: 7
    translator/max_homographs: 7
```

拼音输入法失效，只能输入英文字符。

请问有人知道要如何在安卓端加载语言模型吗？

**Comment by rullineter** [comment]
我自己在安卓端，只要加上语言模型的配置，就会导致中文输入法失效，只能输入英文。
请问有人在安卓端加载过语言模型成功的吗？

**Comment by gaboolic** [comment]
群 696353204
没听人说过安卓不能用语言模型

**Comment by yuannancheng** [comment]
我的 ubuntu 加载语言模型后，打字快了也会直接把预选列表卡没，然后再按键盘，就只能输出英文了。

我用的是万象语言模型

`rime_frost.custom.yaml`

```
patch:
  grammar: # 语言模型
    language: wanxiang-lts-zh-hans
    collocation_max_length: 6
    collocation_min_length: 3
    collocation_penalty: -14
    non_collocation_penalty: -6
    weak_collocation_penalty: -100
    rear_penalty: -20
  translator/contextual_suggestions: false
  translator/max_homophones: 8
```
