### ISSUE TITLE
，。翻页无效

### ISSUE THREAD

**Issue by pengxiaochao** [gaboolic/rime-frost#33]
不管是在default.custom.yml增加
```yaml
patch:
  # 快捷键
  key_binder:
    # Lua 配置: 以词定字（上屏当前词句的第一个或最后一个字），和中括号翻页有冲突
    select_first_character: "bracketleft"  # 左中括号 [
    select_last_character: "bracketright"  # 右中括号 ]

    bindings:
      # 翻页 , .
      - { when: paging, accept: comma, send: Page_Up }
      - { when: has_menu, accept: period, send: Page_Down }
   ```
还是直接放开default.yml
```yaml
    # 翻页 , .
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }
```
按下，。会直接上屏，候选词不会翻页
