### ISSUE TITLE
简拼 版本

### ISSUE THREAD

**Issue by atlantis451** [gaboolic/rime-frost#44]
请求发布 简拼 版本词库
- 简拼 只需要输入首字母
简拼，如输入"mggjdytmgzbtdgg"可以得到 `每个国家都有他们各自不同的国歌`
![](https://raw.githubusercontent.com/gaboolic/rime-frost/master/others/img/mggjdgg.png)

**Comment by Junwu-Git** [comment]
？？？不要声母？？？

**Comment by gaboolic** [comment]
简拼应该是本来就支持的
现在输入输入"mggjdytmgzbtdgg"就可以得到 “每个国家都有他们各自不同的国歌”吧？
```
# 拼写设定
speller:
  # 如果不想让什么标点直接上屏，可以加在 alphabet，或者编辑标点符号为两个及以上的映射
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA`/
  # initials 定义仅作为始码的按键，排除 ` 让单个的 ` 可以直接上屏
  initials: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"  # 第一位<空格>是拼音之间的分隔符；第二位<'>表示可以手动输入单引号来分割拼音。
  algebra:
    - abbrev/^([a-z]).+$/$1/   # 超级简拼
    - abbrev/^([zcs]h).+$/$1/  # 超级简拼中，zh ch sh 视为整体（ch'sh → 城市），而不是像这样分开（c'h's'h → 吃好睡好）。

```
