### ISSUE TITLE
请问是否可以让squirrel.custom.yaml生效呢？

### ISSUE THREAD

**Issue by Boxer-egg** [gaboolic/rime-frost#86]
目前还只是squirrel.yaml生效。
我怕下回git pull的时候把我设置的皮肤改了.

我还尝试了在default.custom.yaml里修改：

```
patch:
  style/color_scheme: clean_white
 或
patch:
  style:
    color_scheme: clean_white
```
都不生效

是我找错了文件，还是有其他方法呢？
