### ISSUE TITLE
自带的几个皮肤和最新版squirrel不兼容，无法横排展示

### ISSUE THREAD

**Issue by SuperNG6** [gaboolic/rime-frost#93]
测试了几个主题，发现存在横排变竖排的情况hengpaibianshupai
<img width="623" alt="image" src="https://github.com/user-attachments/assets/1681e650-7bf7-420c-b710-7c9235658d48">
除了WeChat 主题外好像都存在这个问题

```

    solarized_rock:
      name: 日光石
      horizontal: true # true横排，false竖排
      candidate_format: "%c %@ " # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 6 # 窗口圆角
      font_point: 21 # 候选文字大小
      label_font_point: 15 # 候选编号大小
      line_spacing: 10 # 行间距(适用于竖排)
      font_face: "PingFangSC-Regular,HanaMinB" # 候选词字体
      text_color: 0x8236d3 # 拼音行文字颜色
      back_color: 0x362b00 # 候选条背景色，24位色值，16进制，BGR顺序
      candidate_text_color: 0x969483 # 预选项文字颜色
      comment_text_color: 0xc098a12a # 拼音等提示文字颜色
      hilited_text_color: 0x98a12a # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0x444444 # 第一候选项背景背景色
      hilited_candidate_label_color: 0xfafafa # 第一候选项编号颜色
      hilited_candidate_back_color: 0x8236d3 # 候选文字背景色
      hilited_candidate_text_color: 0xffffff # 第一候选项文字颜色
      ```
